### ISSUE TITLE
metronome at the bottom

### ISSUE THREAD

**Issue by rqcy** [fr3ts0n/StageFever#1]
Hi, thank you for the app.  I find it very useful when playing with the band.

I was wandering, if you could add a visual metronome, e.g., at the bottom of the main screen.  At the moment the beat rate is indicated by a small blinking button, but it's not well visible from a distance.  I was thinking about some kind of a moving ball or larger blinking areas at the bottom of the app.

Thanks again!

**Comment by fr3ts0n** [comment]
Thanks for your input.

Feature is implemented with V1.0.5.
It should be available in F-Droid soon ...

**Comment by fr3ts0n** [comment]
Sorry, V1.0.5 is out rhere already.
I will create V1.0.6 for that.

**Comment by rqcy** [comment]
awesome!

I hope that the new version will be soon in f-droid :)

Thanks!
