### ISSUE TITLE
multi-line notes ?

### ISSUE THREAD

**Issue by jp8** [fr3ts0n/StageFever#6]
This app is very useful.

Is there a way to make a line-break or carriage return in the notes field?  I would like to use it for song lyrics...

**Comment by fr3ts0n** [comment]
Yes it is possible.

Just export the csv multi line text fields within double quotes ("), then the multiple lines will be imported.

This is usually an export option of common spreadsheet programs for all text entries.

**Comment by jp8** [comment]
Perfect thank you so much.
